# Generated by Django 2.0.2 on 2018-05-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180529_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
